## Rigid Body Sandbox

In [1]:
import numpy as np

In [6]:
np.random.rand()

0.8044905306695498

In [8]:
np.random.rand(2)

array([0.92595849, 0.88337758])

In [47]:
np.random.randint(3, 10)

5

In [50]:
np.array([3, 4, 5]) % [3, 4, 3]

array([0, 0, 2])

In [52]:
np.argmax([1, 2, 3])

2

In [4]:
np.array([[1, 2],
          [3, 4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
row1 = np.array([1, 2])
row2 = np.array([3, 4])
J = np.array([row1, row2])
J

array([[1, 2],
       [3, 4]])

In [10]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [4]:
np.maximum([1, 2, 3], [-1, 4, 0])

array([1, 4, 3])

In [5]:
{2, 1} in [{1, 2}]

True

In [8]:
{1, 2} | {1, 3}

{1, 2, 3}

In [12]:
s = set()
s.add(4)
s

{4}

In [18]:
{2, 13} in {frozenset({1, 2})}

False

In [19]:
poop = np.array([1, 2]), np.array([3, 4])
poop + np.array([-1, 1])

array([[0, 3],
       [2, 5]])

In [40]:
h = {frozenset({3, 4}): (np.array([3, 4, 5]), np.array([7, 8, 9])), frozenset(5, 6): (np.array([7, 5, 3]), np.array([5, 3, 3]))}]
h[frozenset({3, 4})

SyntaxError: unmatched ']' (688554061.py, line 1)

In [41]:
np.zeros(3)

array([0., 0., 0.])

In [45]:
d = {'hi': 3}
d['bye'] = 4
d

{'hi': 3, 'bye': 4}

In [48]:
l = [1, 2, 3, 4]
n = len(l)
l = np.reshape(l, (int(n/2), 2))
print(l[1])

[3 4]


In [55]:
def poop():
    return 5, 6

blah = poop()
x, y = blah
x

5