## Rigid Body Sandbox

In [2]:
import numpy as np

In [6]:
np.random.rand()

0.8044905306695498

In [8]:
np.random.rand(2)

array([0.92595849, 0.88337758])

In [47]:
np.random.randint(3, 10)

5

In [50]:
np.array([3, 4, 5]) % [3, 4, 3]

array([0, 0, 2])

In [52]:
np.argmax([1, 2, 3])

2

In [4]:
np.array([[1, 2],
          [3, 4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
row1 = np.array([1, 2])
row2 = np.array([3, 4])
J = np.array([row1, row2])
J

array([[1, 2],
       [3, 4]])

In [10]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])